# ============================================================
# hypridle.conf
# ============================================================

general {
    lock_cmd        = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Reduzir brilho após 3 minutos
listener {
    timeout  = 180
    on-timeout  = brightnessctl -s set 20%
    on-resume   = brightnessctl -r
}

# Bloquear após 5 minutos
listener {
    timeout  = 300
    on-timeout  = loginctl lock-session
}

# Desligar tela após 6 minutos
listener {
    timeout  = 360
    on-timeout  = hyprctl dispatch dpms off
    on-resume   = hyprctl dispatch dpms on
}

# Suspender após 30 minutos
listener {
    timeout  = 1800
    on-timeout  = systemctl suspend
}
