# ============================================================
# hyprpaper.conf
# Coloque seu wallpaper em ~/Pictures/wallpaper.png
# ou ajuste o caminho abaixo
# ============================================================

preload  = ~/Pictures/wallpaper.png
wallpaper = , ~/Pictures/wallpaper.png
splash = false
