# ============================================================
# Catppuccin Abyss — kitty.conf
# ============================================================

# ---- Fonte ----
font_family      JetBrainsMonoNerdFontPropo
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# ---- Cursor ----
cursor_shape         beam
cursor_blink_interval 0.5
cursor_trail          1

# ---- Scrollback ----
scrollback_lines 10000
wheel_scroll_min_lines 1

# ---- Mouse ----
mouse_hide_wait 3.0
url_style curly
detect_urls yes

# ---- Performance ----
repaint_delay    8
input_delay      2
sync_to_monitor  yes

# ---- Janela ----
remember_window_size  no
initial_window_width  900
initial_window_height 560
window_padding_width   14
window_margin_width    0
hide_window_decorations yes
confirm_os_window_close 0

# ---- Blur / transparência (respeitada pelo Hyprland windowrule) ----
background_opacity 0.90
dynamic_background_opacity yes

# ---- Abas ----
tab_bar_edge            top
tab_bar_style            powerline
tab_powerline_style      slanted
tab_title_template       "{title}"

# ---- Layout ----
enabled_layouts splits,stack,tall,fat

# ---- Atalhos ----
map ctrl+shift+enter  new_window
map ctrl+shift+w      close_window
map ctrl+shift+t      new_tab
map ctrl+shift+q      close_tab
map ctrl+shift+right  next_tab
map ctrl+shift+left   previous_tab
map ctrl+shift+c      copy_to_clipboard
map ctrl+shift+v      paste_from_clipboard
map ctrl+plus         change_font_size all +1.0
map ctrl+minus        change_font_size all -1.0
map ctrl+0            change_font_size all 0
map ctrl+shift+f5     load_config_file

# ---- Shell ----
shell zsh
editor code --wait

# ============================================================
# Catppuccin Abyss — cores
# ============================================================
foreground              #CDD6F4
background              #08080D
selection_foreground    #08080D
selection_background    #CBA6F7

cursor                  #CBA6F7
cursor_text_color       #08080D

url_color               #89B4FA

active_border_color     #CBA6F7
inactive_border_color   #45475A
bell_border_color       #F9E2AF

active_tab_foreground   #08080D
active_tab_background   #CBA6F7
inactive_tab_foreground #A6ADC8
inactive_tab_background #11111B
tab_bar_background      #0B0B12

mark1_foreground #08080D
mark1_background #CBA6F7
mark2_foreground #08080D
mark2_background #89B4FA
mark3_foreground #08080D
mark3_background #A6E3A1

color0  #181825
color8  #45475A
color1  #F38BA8
color9  #F38BA8
color2  #A6E3A1
color10 #A6E3A1
color3  #F9E2AF
color11 #F9E2AF
color4  #89B4FA
color12 #89B4FA
color5  #F5C2E7
color13 #F5C2E7
color6  #94E2D5
color14 #94E2D5
color7  #BAC2DE
color15 #A6ADC8
